name: 'Display VerifyML Reports'
description: 'Automated documentation of model and alerts from performance / fairness checks'
author: 'Cylynx Pte Ltd'
inputs:
  cwd:
    description: 'Current working directory'
    required: true
    default: ${{ github.workspace }}
  data-path:
    description: 'Path that store the protobuf file. Example: /data/output/sample.proto'
    required: true
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/main.js'
