name: Display Results

on:
  pull_request:

jobs:
  report-generation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to Current Branch
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Build Dependencies
        run: npm run build

      - name: Generate VerifyML Report
        uses: './'
        with:
          data-path: '/public/data/loan_approval_example.proto'
